In [154]:
import torch
from torch.distributions import Categorical
import numpy as np


In [426]:
action_probs = torch.Tensor([0.3, 0.7])
la = torch.log(action_probs)
print(la)
torch.exp(la)

tensor([-1.2040, -0.3567])


tensor([0.3000, 0.7000])

In [416]:
np.log([0.3, 0.2, 0.5])
pd = Categorical(logits=torch.log(action_probs))

array([-1.2039728 , -1.60943791, -0.69314718])

In [471]:


x = pd.sample()
print(x)
lx = pd.log_prob(x)
print(lx)

tensor(1)
tensor(-0.3567)


In [350]:
action = torch.multinomial(action_probs,1).item()
torch.log(action_probs[action])

tensor(-0.6931)

In [428]:
t = torch.tensor([-1.6094,-0.2231])
print(torch.exp(t))
pdparams = t
pd = Categorical(logits=pdparams)
action = pd.sample()
print(action, pd.log_prob(action))

tensor([0.2000, 0.8000])
tensor(1) tensor(-0.2231)


In [326]:
np.log(action_probs)


tensor([-1.6094, -1.2040, -0.6931])