In [2]:
!pip install gym --user

In [3]:
import gym


In [7]:
import numpy as np # 1. Load Environment and Q-table structure
env = gym.make('FrozenLake-v0')
Q = np.zeros([env.observation_space.n,env.action_space.n])
# env.obeservation.n, env.action_space.n gives number of states and action in env loaded# 2. Parameters of Q-leanring
eta = .628
gma = .9
epis = 5000
rev_list = [] # rewards per episode calculate
# 3. Q-learning Algorithm
for i in range(epis):
    # Reset environment
    s = env.reset()
    rAll = 0
    d = False
    j = 0
        #The Q-Table learning algorithm
    while j < 99:
       # env.render()
        j+=1
        # Choose action from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(j+1)))
        #Get new state & reward from environment
        s1,r,d,_ = env.step(a)
            #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
                break
    rev_list.append(rAll)
        #env.render()
    
print ("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print ("Final Values Q-Table")
print (Q)

Reward Sum on all episodes 0.0348
Final Values Q-Table
[[0.07882991 0.07258253 0.06225658 0.06838252]
 [0.05917275 0.02219412 0.0196884  0.06448568]
 [0.05505914 0.05386261 0.05011751 0.06295193]
 [0.05558174 0.049026   0.00464728 0.05323092]
 [0.08293357 0.02934102 0.14186913 0.03567599]
 [0.         0.         0.         0.        ]
 [0.04159297 0.02675464 0.01725004 0.01294609]
 [0.         0.         0.         0.        ]
 [0.02973929 0.03603065 0.257635   0.19222098]
 [0.05321873 0.12493406 0.15299202 0.01908788]
 [0.14406261 0.03983021 0.07577186 0.019281  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.07974945 0.04072495 0.71192136 0.01958167]
 [0.         0.278264   0.23319674 0.96064554]
 [0.         0.         0.         0.        ]]
