In [14]:
import numpy as np

p = np.array([0.1, 0.2, 0.3, 0.25, 0.15])
print(-np.log(p))
print(np.exp(1-p))

q = 0.5
tsallis = 1/(q-1) * (1 - p**(q-1))
tsallis

[2.30258509 1.60943791 1.2039728  1.38629436 1.89711998]
[2.45960311 2.22554093 2.01375271 2.11700002 2.33964685]


array([4.32455532, 2.47213595, 1.65148372, 2.        , 3.16397779])